[package]
name = "briq_protocol"
version = "2.2.0"
cairo-version = "2.5.4"

[cairo]
sierra-replace-ids = true

[dependencies]
token = { git = "https://github.com/dojoengine/origami.git", rev="16752c58d8b9cd3ca001282b0b815fd14bb62a9b" }

[tool.dojo.world]
name = "briq"
description = "Collect, build and play with briqs, the building blocks of the metaverse."
icon_uri = "file://docs/squarebriq.jpg"
cover_uri = "/Volumes/Samsung_T5/Programming/briq-protocol/docs/banner.png"
website = "https://briq.construction/"
socials.x = "https://twitter.com/briqNFT"

[[target.dojo]]

# build-external-contracts = [
#     'presets::erc1155::erc1155::components::erc_1155_balance',
#     'presets::erc1155::erc1155::components::operator_approval',
#     'presets::erc721::erc721::components::erc_721_balance',
#     'presets::erc721::erc721::components::erc_721_owner',
#     'presets::erc721::erc721::components::erc_721_token_approval'
# ]

#[tool.dojo.env]
# rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
# account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
# private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"

# keystore_password = "password"
# keystore_path = "../keystore.json"
